export const Constants = {
    title: 'Welcome to Asset Manager...',
    minNumberOfAssets: 0,
    maxNumberOfAssets: 401,
    numberOfAssets: 400,
    numOfStockAssets: 200,
    numOfCurrencyAssets: 200,
    priceRange1: '$1-$25',
    priceRange2: '$26-$50',
    priceRange3: '$51-$100',
    priceRange4: 'More than $100',
    minPriceRange1:0,
    maxPriceRange1:26,
    maxPriceRange2:51,
    maxPriceRange3:101,
    updatedToday:'updated Today',
    updateYesterday:'updated Yesterday',
    lastUpdateFilterMessage:'Results are updated frequently. Last update was 1 second ago.',
    stocks: ['AAPL', 'GOOG', 'FB', 'TSLA', 'MSFT'],
    currencies: ['USD', 'EUR', 'GBP', 'NIS', 'AUD'],
    STOCK: 'Stock',
    CURRENCY: 'Currency',
    updateInterval: 1000,
    noAssetsMessage: 'No assets matches the filter criteria.',
    valueIncorrectMessage: 'The filter criteria had incorrect value.'
}